/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.cassandra.utils.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
public class UUID extends org.apache.avro.specific.SpecificFixed {}
