/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.cassandra.avro;

@SuppressWarnings("all")
public enum ConsistencyLevel { 
  ONE, QUORUM, LOCAL_QUORUM, EACH_QUORUM, ALL
}
