/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.cassandra.db.migration.avro;

@SuppressWarnings("all")
public class RenameColumnFamily extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"RenameColumnFamily\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"ksname\",\"type\":\"string\"},{\"name\":\"cfid\",\"type\":\"int\"},{\"name\":\"old_cfname\",\"type\":\"string\"},{\"name\":\"new_cfname\",\"type\":\"string\"}]}");
  public java.lang.CharSequence ksname;
  public int cfid;
  public java.lang.CharSequence old_cfname;
  public java.lang.CharSequence new_cfname;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ksname;
    case 1: return cfid;
    case 2: return old_cfname;
    case 3: return new_cfname;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ksname = (java.lang.CharSequence)value$; break;
    case 1: cfid = (java.lang.Integer)value$; break;
    case 2: old_cfname = (java.lang.CharSequence)value$; break;
    case 3: new_cfname = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
