#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package Cassandra::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant VERSION => "2.1.0";

1;
